# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 董瑞博客 | Rui Blog
name: 董瑞博客
home_title: 白首如新 倾盖如故
home_sub_title: 时间是我们正在服下的毒药，也是未来我们的解药。
keyword: "董瑞, 瑞, dongrui, imrui, ruidong, rui, @imrui, 董瑞博客, 博客, 个人网站, 互联网, 游戏"
qq: 
email: hilo.sky.do@gmail.com
location: Beijing, China
description: > # this means to ignore newlines until "baseurl:"
  走山路就跟走人生的路一样，你不会轻易地知道下一条路在哪里，要怎样走才算对，还要多久才能抵达。错过和遇见都是对等的，没有公平与不公平，但凡小有成就的人，都一定是走了一条别人不愿意走的路，或泥泞不堪，或荆棘丛生。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://imrui.net" # the base hostname & protocol for your site
github_username:  imrui
github_url: https://github.com/imrui
facebook_url: https://www.facebook.com/rui.dong.507
twitter_url: https://twitter.com/imruido
weibo_url: http://weibo.com/qlcr
linkedin_url: http://www.linkedin.com/in/imrui
google_plus_url: https://plus.google.com/u/0/103103594124075490506/posts

# Disque
disque:
  enable: false
  host: imrui.disqus.com

# 多说评论
duoshuo:
  enable: true
  short_name: imruiblog

gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - jekyll-github-metadata
  - kramdown
  - rouge

markdown: kramdown
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input:  GFM
  enable_coderay: true
  syntax_highlighter: rouge

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation
navs:
  -
    href: /
    label: 首页

  -
    href: /blog
    label: 时光机

  -
    href: /bookmark
    label: 书签

  -
    href: /about
    label: 关于

post_category_name: 博文分类
post_nav_name: 文内导航
links_name: 友情链接

links:
  -
    href: https://leetcode.com/
    label: LeetCode

  -
    href: http://fontawesome.io/
    label: Font Awesome

  -
    href: https://stackoverflow.com/
    label: Stack Overflow

  -
    href: http://izayoi617.pixnet.net/blog
    label: 子雲吉他教學 

# Google Analytics
# https://www.google.com/analytics/
google_analytics:
  enable: ture
  id: 'UA-80328712-1'

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# https://www.google.com/cse/
google_cse:
  enable: ture
  cx: 000063965395341567097:bmbju2qjbwy

# http://zn.baidu.com/
baidu_search:
  enable: false
  id: 1132595382140778164
  site: http://zhannei.baidu.com/cse/search

# For about.html. Fell free to create your own!
skill_software_keywords: [Java, Python, Golang, C, lua, MySQL, Android, Linux, Nginx]
skill_j2ee_keywords: [Spring, SpringMVC, MyBatis, Struts, Play Framework, JSP, Velocity]
skill_web_keywords: [Tornado, Flask, Django, AngularJS, Boostrap, HTML, CSS, JS, JQuery, Ajax]
